yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: pnp

packageExtensions:
  '@toast-ui/react-editor@*':
    dependencies:
      '@toast-ui/editor': '*'
  '@toast-ui/editor@*':
    dependencies:
      'codemirror': '*'
      'prosemirror-transform': '*'
