# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2 # Update to the latest version of checkout action
        with:
          fetch-depth: 0
      - name: Setup Node.js with Yarn Berry
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 4.0.2
          yarn set version 4.0.2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn
      - name: Run Chromatic
        uses: chromaui/action@v1 # Update to the latest version of Chromatic action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
